<?xml version="1.0" encoding="UTF-8"?>

-<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://sap-services.edpbr.com.br/WPA/SFRLBaixaPagamento" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://sap-services.edpbr.com.br/WPA/SFRLBaixaPagamento" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:s="http://www.w3.org/2001/XMLSchema">


-<wsdl:types>


-<s:schema targetNamespace="http://sap-services.edpbr.com.br/WPA/SFRLBaixaPagamento" elementFormDefault="qualified">


-<s:element name="Enviar">


-<s:complexType>


-<s:sequence>

<s:element name="credentials" type="tns:Credenciais" maxOccurs="1" minOccurs="0"/>

<s:element name="nota" type="tns:NotaSimples" maxOccurs="1" minOccurs="0"/>

</s:sequence>

</s:complexType>

</s:element>


-<s:complexType name="Credenciais">


-<s:sequence>

<s:element name="AppId" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="AppSecret" type="s:string" maxOccurs="1" minOccurs="0"/>

</s:sequence>

</s:complexType>


-<s:complexType name="NotaSimples">


-<s:sequence>

<s:element name="Empresa" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Numero" type="s:string" maxOccurs="1" minOccurs="0"/>

</s:sequence>

</s:complexType>


-<s:element name="EnviarResponse">


-<s:complexType>


-<s:sequence>

<s:element name="EnviarResult" type="tns:Retorno" maxOccurs="1" minOccurs="0"/>

</s:sequence>

</s:complexType>

</s:element>


-<s:complexType name="Retorno">


-<s:sequence>

<s:element name="NumeroNota" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="TipoMensagem" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Mensagem" type="s:string" maxOccurs="1" minOccurs="0"/>

</s:sequence>

</s:complexType>

</s:schema>

</wsdl:types>


-<wsdl:message name="EnviarSoapIn">

<wsdl:part name="parameters" element="tns:Enviar"/>

</wsdl:message>


-<wsdl:message name="EnviarSoapOut">

<wsdl:part name="parameters" element="tns:EnviarResponse"/>

</wsdl:message>


-<wsdl:portType name="SFRLBAixaPagamentoSoap">


-<wsdl:operation name="Enviar">

<wsdl:input message="tns:EnviarSoapIn"/>

<wsdl:output message="tns:EnviarSoapOut"/>

</wsdl:operation>

</wsdl:portType>


-<wsdl:binding name="SFRLBAixaPagamentoSoap" type="tns:SFRLBAixaPagamentoSoap">

<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>


-<wsdl:operation name="Enviar">

<soap:operation style="document" soapAction="http://sap-services.edpbr.com.br/WPA/SFRLBaixaPagamento/Enviar"/>


-<wsdl:input>

<soap:body use="literal"/>

</wsdl:input>


-<wsdl:output>

<soap:body use="literal"/>

</wsdl:output>

</wsdl:operation>

</wsdl:binding>


-<wsdl:binding name="SFRLBAixaPagamentoSoap12" type="tns:SFRLBAixaPagamentoSoap">

<soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>


-<wsdl:operation name="Enviar">

<soap12:operation style="document" soapAction="http://sap-services.edpbr.com.br/WPA/SFRLBaixaPagamento/Enviar"/>


-<wsdl:input>

<soap12:body use="literal"/>

</wsdl:input>


-<wsdl:output>

<soap12:body use="literal"/>

</wsdl:output>

</wsdl:operation>

</wsdl:binding>


-<wsdl:service name="SFRLBAixaPagamento">


-<wsdl:port name="SFRLBAixaPagamentoSoap" binding="tns:SFRLBAixaPagamentoSoap">

<soap:address location="http://localhost/cond/sfrl/WPA/SFRLBAixaPagamento.asmx"/>

</wsdl:port>


-<wsdl:port name="SFRLBAixaPagamentoSoap12" binding="tns:SFRLBAixaPagamentoSoap12">

<soap12:address location="http://localhost/cond/sfrl/WPA/SFRLBAixaPagamento.asmx"/>

</wsdl:port>

</wsdl:service>

</wsdl:definitions>