<?xml version="1.0" encoding="UTF-8"?>

-<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://sap-services.edpbr.com.br/DD" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://sap-services.edpbr.com.br/DD" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:s="http://www.w3.org/2001/XMLSchema">


-<wsdl:types>


-<s:schema targetNamespace="http://sap-services.edpbr.com.br/DD" elementFormDefault="qualified">


-<s:element name="Enviar">


-<s:complexType>


-<s:sequence>

<s:element name="credentials" type="tns:Credenciais" maxOccurs="1" minOccurs="0"/>

<s:element name="nota" type="tns:DDNota" maxOccurs="1" minOccurs="0"/>

</s:sequence>

</s:complexType>

</s:element>


-<s:complexType name="Credenciais">


-<s:sequence>

<s:element name="AppId" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="AppSecret" type="s:string" maxOccurs="1" minOccurs="0"/>

</s:sequence>

</s:complexType>


-<s:complexType name="DDNota">


-<s:sequence>

<s:element name="Empresa" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Numero" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Tipo" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Setor" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Causa" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="TipoManutencao" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Data" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="ConclusaoDesejada" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="GPM" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="CodigoCliente" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Telefone" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Rua" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Bairro" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Cidade" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="CEP" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Endereco" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Circuito" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="LocalInstalacao" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Equipamento" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Conjunto" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="DescricaoConjunto" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="CodigoMedidas" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Texto" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="EquipamentoEletrico" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="DescricaoProblema" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="DescricaoOperacao" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Componente" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="ReferenciaEletrica" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="IdPosteCaixaEt" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="CoordenadaPeeLatitude" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="CoordenadaPeeLongitude" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Observacoes" type="s:string" maxOccurs="1" minOccurs="0"/>

</s:sequence>

</s:complexType>


-<s:element name="EnviarResponse">


-<s:complexType>


-<s:sequence>

<s:element name="EnviarResult" type="tns:Retorno" maxOccurs="1" minOccurs="0"/>

</s:sequence>

</s:complexType>

</s:element>


-<s:complexType name="Retorno">


-<s:sequence>

<s:element name="NumeroNota" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="TipoMensagem" type="s:string" maxOccurs="1" minOccurs="0"/>

<s:element name="Mensagem" type="s:string" maxOccurs="1" minOccurs="0"/>

</s:sequence>

</s:complexType>

</s:schema>

</wsdl:types>


-<wsdl:message name="EnviarSoapIn">

<wsdl:part name="parameters" element="tns:Enviar"/>

</wsdl:message>


-<wsdl:message name="EnviarSoapOut">

<wsdl:part name="parameters" element="tns:EnviarResponse"/>

</wsdl:message>


-<wsdl:portType name="DDSoap">


-<wsdl:operation name="Enviar">

<wsdl:input message="tns:EnviarSoapIn"/>

<wsdl:output message="tns:EnviarSoapOut"/>

</wsdl:operation>

</wsdl:portType>


-<wsdl:binding name="DDSoap" type="tns:DDSoap">

<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>


-<wsdl:operation name="Enviar">

<soap:operation style="document" soapAction="http://sap-services.edpbr.com.br/DD/Enviar"/>


-<wsdl:input>

<soap:body use="literal"/>

</wsdl:input>


-<wsdl:output>

<soap:body use="literal"/>

</wsdl:output>

</wsdl:operation>

</wsdl:binding>


-<wsdl:binding name="DDSoap12" type="tns:DDSoap">

<soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>


-<wsdl:operation name="Enviar">

<soap12:operation style="document" soapAction="http://sap-services.edpbr.com.br/DD/Enviar"/>


-<wsdl:input>

<soap12:body use="literal"/>

</wsdl:input>


-<wsdl:output>

<soap12:body use="literal"/>

</wsdl:output>

</wsdl:operation>

</wsdl:binding>


-<wsdl:service name="DD">


-<wsdl:port name="DDSoap" binding="tns:DDSoap">

<soap:address location="http://localhost/cond/dd/DD.asmx"/>

</wsdl:port>


-<wsdl:port name="DDSoap12" binding="tns:DDSoap12">

<soap12:address location="http://localhost/cond/dd/DD.asmx"/>

</wsdl:port>

</wsdl:service>

</wsdl:definitions>